---
kind: ClusterSecretStore
apiVersion: external-secrets.io/v1
metadata:
  name: kube-system-secret-store
spec:
  provider: 
    kubernetes:
      remoteNamespace: kube-system
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
      auth:
        serviceAccount:
          name: external-secrets
          namespace: kube-system