---
kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  namespace: clustersecret
  name: dockerconfig-github-com
avoidNamespaces:
  - kube-*
  - flux-system
  - cert-manager
data:
  valueFrom:
    secretKeyRef:
      name: dockerconfig-github-com
      namespace: kube-system