---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alterconso
  namespace: alterconso
spec:
  values:
    webapp:
      env_as_values:
        MYSQL_ROOT_PASSWORD: AgCTLgLh1iLUwn7kFuUvvunVIf7MISXhKhI5ICFhawsXHM0nOThLO7luwcqlb4Px3fbozstVhC3cOS7CBc8GRgNymp+3sq6yokLnQo20p5P3BAXTlx0QHFAmgBp+rzzaxypDc08BxrASKCncPv3DiACd4v5qungCnT3o5kqHmBv4oQyVVx1z9ZNctzOp3DbqEOEokphQoWbwds+LQSwBwCQwDLbETdvbOQqDaj9CyiJWajkLYEO7JqIEh3Wuf9aZ9Z3O0INIvpRZn9Ed8UPp1PZf7CltitmTcWk84gN5ERb25hVqZcN3STu8tE3bwsZBZFnAjqwirOOHDouoLcC+oIvgVadOk6mm789k7fxhp9e4rgFS3z1ONAZeM6ZM/sWuSW/YktQrGhx+/9d4KNyy1onR6GFDe+xteSmbSzldTXWtX+eRGUq4ztg6M1yuXntVb9cEfAS6zY5f8KAlF7AsFYWQnMZUTbQrQt5vgLf+w7tUlAy43Eb9xeyhJ1oSN1YyuxNJYEjg1kiYn5vWOOfwHjmQChVxagG6yuawLC8k5JD/XNYZ1YSkNnVSprzAxwSkdjOVajnSZjaSXdW5nNS6E0E4vwcr9uYS1aS/RxkfVhNefDOEAH4K3MCJrH6j1mbt9udwCREBf7bFh53PsZ51OduzdcYfvslZjykkfBRqI9lLr1QPecS1r3RmYDkOoe2F9GgTqO3Ixw=
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: "mkcert-issuer"
        hosts:
          - name: alterconso.gpenaud.localhost
            path: /
            tls: true
      vhost: alterconso.gpenaud.localhost
    database:
      env:
        MYSQL_PASSWORD: alterconso
      env_as_secrets:
        MYSQL_ROOT_PASSWORD: AgCTLgLh1iLUwn7kFuUvvunVIf7MISXhKhI5ICFhawsXHM0nOThLO7luwcqlb4Px3fbozstVhC3cOS7CBc8GRgNymp+3sq6yokLnQo20p5P3BAXTlx0QHFAmgBp+rzzaxypDc08BxrASKCncPv3DiACd4v5qungCnT3o5kqHmBv4oQyVVx1z9ZNctzOp3DbqEOEokphQoWbwds+LQSwBwCQwDLbETdvbOQqDaj9CyiJWajkLYEO7JqIEh3Wuf9aZ9Z3O0INIvpRZn9Ed8UPp1PZf7CltitmTcWk84gN5ERb25hVqZcN3STu8tE3bwsZBZFnAjqwirOOHDouoLcC+oIvgVadOk6mm789k7fxhp9e4rgFS3z1ONAZeM6ZM/sWuSW/YktQrGhx+/9d4KNyy1onR6GFDe+xteSmbSzldTXWtX+eRGUq4ztg6M1yuXntVb9cEfAS6zY5f8KAlF7AsFYWQnMZUTbQrQt5vgLf+w7tUlAy43Eb9xeyhJ1oSN1YyuxNJYEjg1kiYn5vWOOfwHjmQChVxagG6yuawLC8k5JD/XNYZ1YSkNnVSprzAxwSkdjOVajnSZjaSXdW5nNS6E0E4vwcr9uYS1aS/RxkfVhNefDOEAH4K3MCJrH6j1mbt9udwCREBf7bFh53PsZ51OduzdcYfvslZjykkfBRqI9lLr1QPecS1r3RmYDkOoe2F9GgTqO3Ixw==
      local:
        path: /mnt/k3s/alterconso
      nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - t490s
