---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alterconso
  namespace: alterconso
spec:
  values:
    webapp:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: "mkcert-issuer"
        hosts:
          - name: alterconso.gpenaud.localhost
            path: /
            tls: true
      vhost: alterconso.gpenaud.localhost
    database:
      local:
        path: /mnt/k3s/alterconso
      nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - t490s
