---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alterconso
resources:
  - ../base/alterconso
patches:
  - path: alterconso-values.yaml
    target:
      kind: HelmRelease
