---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/alterconso
patches:
  - path: alterconso-values.yaml
    target:
      kind: HelmRelease
  - target:
      kind: ImageUpdateAutomation
      name: alterconso
    patch: |
      - op: replace
        path: /spec/update/path
        value: ./apps/localhost