---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alterconso
  namespace: alterconso
spec:
  releaseName: alterconso
  chart:
    spec:
      chart: alterconso
      sourceRef:
        kind: HelmRepository
        name: alterconso
  interval: 5m
  timeout: 1m
  install:
    remediation:
      retries: 3
  values:
    webapp:
      image:
        repository: ghcr.io/gpenaud/alterconso # {"$imagepolicy": "alterconso:alterconso:name"}
        tag: 1.0.0 # {"$imagepolicy": "alterconso:alterconso:tag"}
