---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerconfig-github-com
  namespace: alterconso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-system-secret-store
  target:
    name: dockerconfig-github-com
  dataFrom:
    - extract:
        key: dockerconfig-github-com
