---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerconfigjson-github-com
  namespace: alterconso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-system-secret-store
  target:
    name: dockerconfigjson-github-com
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: dockerconfigjson-github-com
